title: Workflows for Data Analysts
author: Lewis Meineke
email: meineke@uchicago.edu
description: A collection of workshop materials on using Linux, SSH, git, and GitHub in everyday workflows

theme: minima
favicon: assets/favicon.ico
